twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        "%kernel.project_dir%/public": public_path
        "%kernel.project_dir%/public/uploads/media": media_uploads_path
    form_themes:
        - 'admin/inputs/NavType.html.twig'
        - 'admin/inputs/ThumbnailType.html.twig'
        - 'admin/inputs/FieldsRelationType.html.twig'
        - 'admin/inputs/FieldSetType.html.twig'
        - 'admin/inputs/GroupType.html.twig'
        - 'admin/inputs/FiltersType.html.twig'
        - 'admin/inputs/VariantsCollectionType.html.twig'
        - 'admin/inputs/EditorType.html.twig'
        - 'admin/inputs/FaqType.html.twig'
        - 'admin/inputs/LabelsType.html.twig'
        - 'admin/inputs/GalleryType.html.twig'
when@test:
    twig:
        strict_variables: true
